// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace ResumeAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20260312084802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("GPA")
                        .HasColumnType("double precision");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ResumeAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResumeAnalysisId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.JobMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIFeedBack")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResumeAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("_matchingSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MatchingSkills");

                    b.Property<string>("_missingSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MissingSkills");

                    b.HasKey("Id");

                    b.HasIndex("ResumeAnalysisId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("_skills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Skills");

                    b.Property<string>("_strengths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Strengths");

                    b.Property<string>("_suggestions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Suggestions");

                    b.Property<string>("_weaknesses")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Weaknesses");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("ResumeAnalyses");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ResumeAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_responsibilities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Responsibilities");

                    b.HasKey("Id");

                    b.HasIndex("ResumeAnalysisId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.Education", b =>
                {
                    b.HasOne("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", null)
                        .WithMany("Educations")
                        .HasForeignKey("ResumeAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.JobMatch", b =>
                {
                    b.HasOne("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", null)
                        .WithMany("JobMatches")
                        .HasForeignKey("ResumeAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.HasOne("ResumeAnalyzer.Domain.Entities.Resume", null)
                        .WithOne("Analysis")
                        .HasForeignKey("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ResumeAnalyzer.Domain.ValueObjects.PersonelInfo", "PersonelInfo", b1 =>
                        {
                            b1.Property<Guid>("ResumeAnalysisId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("GitHubUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("LinkedInUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Summary")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("ResumeAnalysisId");

                            b1.ToTable("ResumeAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("ResumeAnalysisId");
                        });

                    b.Navigation("PersonelInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", null)
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ResumeAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.Resume", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ResumeAnalyzer.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("JobMatches");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
